Fake a JUnit ExtensionPoint to get the unit test to "run"
Throwing a NoClassDefFoundError for some JUnit classes, but
I think if we can get the JUnit lib on the classpath then
it'll work just fine. Will need to double check to see whether it's
a unit test environment issue or if this also occurs in production