Add explicit MaxPermSize jvm option
The tests keeps OOMing on Travis due to PermGen, specifically:

org.intellivim.core.command.test.TestTest > testMocksWorked
java.io.IOException: java.lang.OutOfMemoryError: PermGen space
at com.intellij.openapi.project.impl.ProjectManagerImpl.convertAndLoadProject(ProjectManagerImpl.java:583)
at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:537)
at org.intellivim.core.util.ProjectUtil$1.run(ProjectUtil.java:98)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:302)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:738)
...
Caused by: java.lang.OutOfMemoryError: PermGen space
java.io.IOException: :(
at org.intellivim.core.util.ProjectUtil.getProject(ProjectUtil.java:114)
at org.intellivim.core.util.ProjectUtil.ensureProject(ProjectUtil.java:52)
at org.intellivim.UsableSdkTestCase.tearDown(UsableSdkTestCase.java:106)
at junit.framework.TestCase.runBare(TestCase.java:130)
at com.intellij.testFramework.UsefulTestCase.defaultRunBare(UsefulTestCase.java:335)
at com.intellij.testFramework.UsefulTestCase.runBare(UsefulTestCase.java:358)